; name lengths
DEF NAME_LENGTH        EQU 11
DEF PLAYER_NAME_LENGTH EQU 8
DEF BOX_NAME_LENGTH    EQU 9
DEF MON_NAME_LENGTH    EQU 11
DEF MOVE_NAME_LENGTH   EQU 13
DEF ITEM_NAME_LENGTH   EQU 13
DEF TRAINER_CLASS_NAME_LENGTH EQU 13

; see home/text.asm
DEF BORDER_WIDTH   EQU 2
DEF TEXTBOX_WIDTH  EQU SCREEN_WIDTH
DEF TEXTBOX_INNERW EQU TEXTBOX_WIDTH - BORDER_WIDTH
DEF TEXTBOX_HEIGHT EQU 6
DEF TEXTBOX_INNERH EQU TEXTBOX_HEIGHT - BORDER_WIDTH
DEF TEXTBOX_X      EQU 0
DEF TEXTBOX_INNERX EQU TEXTBOX_X + 1
DEF TEXTBOX_Y      EQU SCREEN_HEIGHT - TEXTBOX_HEIGHT
IF DEF(LANG_ZH)
; 汉字字形落在 2x2 个 tile 单元里，正文每行要占 2 个 tile 行。
; 内框只有 TEXTBOX_INNERH (= 4) 行，而英文正文只用到其中 3 行（14/16，行 13 是余量），
; 所以中文必须把正文顶边抬高 1 行才能放下两行：
;   第一行 = 行 13-14，第二行 = 行 15-16，正好铺满内框且不碰到边框（行 12 与行 17）。
; 注意不要改成缩小 TEXTBOX_HEIGHT 之类的方案：文本框顶边一旦上移，
; 战斗界面的己方 HP 条（行 9-11）就会被盖住。
DEF TEXTBOX_INNERY EQU TEXTBOX_Y + 1
ELSE
DEF TEXTBOX_INNERY EQU TEXTBOX_Y + 2
ENDC

; see gfx/frames/*.png
DEF TEXTBOX_FRAME_TILES EQU 8

; PrintNum bit flags
	const_def 4
	const PRINTNUM_DELAY_F        ; 4
	const PRINTNUM_MONEY_F        ; 5
	const PRINTNUM_LEFTALIGN_F    ; 6
	const PRINTNUM_LEADINGZEROS_F ; 7

; PrintNum arguments (see engine/math/print_num.asm)
DEF PRINTNUM_DELAY        EQU 1 << PRINTNUM_DELAY_F
DEF PRINTNUM_MONEY        EQU 1 << PRINTNUM_MONEY_F
DEF PRINTNUM_LEFTALIGN    EQU 1 << PRINTNUM_LEFTALIGN_F
DEF PRINTNUM_LEADINGZEROS EQU 1 << PRINTNUM_LEADINGZEROS_F
