; 自动生成，请勿手改（由 tools/zh/zh.py gen-font 产出）
DEF ZH_GLYPH_COUNT     EQU 1628
DEF ZH_GLYPH_SIZE      EQU 32
DEF ZH_GLYPHS_PER_BANK EQU 512
DEF ZH_GLYPH_BANK_COUNT EQU 4
DEF ZH_GLYPH_BANK_SHIFT EQU 9

IF ZH_GLYPH_COUNT > 8576
	FAIL "字形数超过双字节编码容量"
ENDC
ASSERT ZH_GLYPH_SIZE * ZH_GLYPHS_PER_BANK == $4000
ASSERT 1 << ZH_GLYPH_BANK_SHIFT == ZH_GLYPHS_PER_BANK
